field.formatter.third_party.field_multiple_limit:
  type: mapping
  label: 'Field Multiple Limit entity display settings'
  mapping:
    limit_values:
      type: boolean
      label: 'Limit values'
    count:
      type: integer
      label: Count
    offset:
      type: integer
      label: Offset
